spring:
  cloud:
    gateway:
      routes:
        #商品路由
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/mallproduct/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        #第三方路由
        - id: third-party-route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        #会员服务路由
        - id: member-route
          uri: lb://mall-member
          predicates:
            - Path=/api/mallmember/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}


        #库存服务
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/mallware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}


        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

# 前端项目发送请求 都带上api